version: '3.8'

services:

  # POSTGRES docker run --name postgres-database --network micro -e POSTGRES_PASSWORD=Aforo255#2019  -d -p 5434:5432  postgres
  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Aforo255#2019
    networks:
      - aforo255-test

  # MYSQL docker run --name mysql-database --network micro  -e MYSQL_ROOT_PASSWORD=Aforo255#2019 -p 3307:3306 -p 33061:33060 -d mysql
  mysql-db:
    container_name: mysql-db
    image: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=Aforo255#2019
    networks:
      - aforo255-test

  # MONGO docker run -p 27018:27017 --network micro --name mongo-database -d mongo
  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - 27017:27017
    networks:
      - aforo255-test

  sqlserver-db:
    container_name: sqlserver-db
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Aforo255#2019
      - ACCEPT_EULA=Y
    networks:
      - aforo255-test

  # CONFIG docker run -d --name config-service -p 8888:8888 -e SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/ivancuadros1988/msconfig  hyness/spring-cloud-config-server
  config-service-test:
    container_name: config-service-test
    image: hyness/spring-cloud-config-server
    ports:
      - 8888:8888
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/mdmg92/ms-test-config
    networks:
      - aforo255-test

  # RABBIT MQ docker run -d -p 15672:15672 -p 5672:5672 --name rabbitmq-service rabbitmq:3-management
  bus-service-test:
    container_name: bus-service-test
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - aforo255-test

  # CONSUL docker run --name consul-service --network micro -p 8500:8500 -d consul
  consul-service-test:
    container_name: consul-service-test
    image: consul
    ports:
      - 8500:8500
    networks:
      - aforo255-test

  # FABIO docker run --name fabio-service -e FABIO_REGISTRY_CONSUL_ADDR=consul-service:8500 -p 9998:9998 -p 9999:9999 -d --network micro  fabiolb/fabio
  balance-service-test:
    container_name: balance-service-test
    image: fabiolb/fabio
    ports:
      - 9998:9998
      - 9999:9999
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul-service-test:8500
    networks:
      - aforo255-test
    depends_on:
      - consul-service-test
  
  app-invoices:
    container_name: app-invoices
    build: 
      context: .
      dockerfile: src/AFORO255.MS.TEST.Invoice/Dockerfile
    environment: 
      - Consul:Service=app-invoices
      - Consul:Address=app-invoices
      - Consul:Port=80
      - Fabio:Service=app-invoices
    ports:
      - 5002:80
    networks:
      - aforo255-test
    depends_on:
      - config-service-test
      - consul-service-test
      - balance-service-test
      - bus-service-test
      - postgres-db

networks:
  aforo255-test:
    name: aforo255-test
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: aforo255-test