version: '3.8'

services:

  # POSTGRES docker run --name postgres-database --network micro -e POSTGRES_PASSWORD=Aforo255#2019  -d -p 5434:5432  postgres
  postgres-ms:
    container_name: postgres-ms
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Aforo255#2019
    networks:
      - aforo255-test

  # CONFIG docker run -d --name config-service -p 8888:8888 -e SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/ivancuadros1988/msconfig  hyness/spring-cloud-config-server
  config-service-test:
    container_name: config-server
    image: hyness/spring-cloud-config-server
    ports:
      - 8889:8888
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/mdmg92/ms-test-config
    networks:
      - aforo255-test
networks:
  aforo255-test:
    name: aforo255-test
    driver: bridge